ADR_COUNTRY_MAP = \n{'ABB': 'Unknown',
 'ABEV': 'Brazil',
 'AC': 'Canada',
 'AEM': 'Canada',
 'AIQUY': 'France',
 'ARM': 'United Kingdom',
 'ASX': 'Taiwan',
 'AUO': 'Taiwan',
 'AXAHY': 'France',
 'AZN': 'United Kingdom',
 'BABA': 'China',
 'BASFY': 'Germany',
 'BAYRY': 'Germany',
 'BBD': 'Brazil',
 'BBDO': 'Brazil',
 'BCE': 'Canada',
 'BEKE': 'China',
 'BGNE': 'Unknown',
 'BHP': 'Australia',
 'BIDU': 'China',
 'BILI': 'China',
 'BMO': 'Canada',
 'BMWYY': 'Germany',
 'BNPQY': 'France',
 'BNS': 'Canada',
 'BP': 'United Kingdom',
 'BSBR': 'Brazil',
 'BTI': 'United Kingdom',
 'CAJ': 'Unknown',
 'CAN': 'Singapore',
 'CHT': 'Taiwan',
 'CIG': 'Brazil',
 'CM': 'Canada',
 'CNQ': 'Canada',
 'DAO': 'China',
 'DB': 'Germany',
 'DEO': 'United Kingdom',
 'DTEGY': 'Germany',
 'EBR': 'Unknown',
 'EDU': 'China',
 'ENB': 'Canada',
 'ERJ': 'Unknown',
 'FUTU': 'Hong Kong',
 'GGB': 'Brazil',
 'GOLD': 'United States',
 'GSK': 'United Kingdom',
 'HDB': 'India',
 'HMC': 'Japan',
 'HSBC': 'Hong Kong',
 'HTHT': 'China',
 'HUYA': 'China',
 'IBN': 'India',
 'INFY': 'India',
 'IQ': 'China',
 'ITUB': 'Brazil',
 'IX': 'Japan',
 'JD': 'China',
 'KB': 'South Korea',
 'KEP': 'South Korea',
 'KMTUY': 'Japan',
 'KNBWY': 'Japan',
 'KT': 'South Korea',
 'LI': 'China',
 'LPL': 'South Korea',
 'LU': 'China',
 'LYG': 'United Kingdom',
 'MBGYY': 'Germany',
 'MFC': 'Canada',
 'MFG': 'Japan',
 'MNSO': 'China',
 'MUFG': 'Japan',
 'NGG': 'United Kingdom',
 'NIO': 'China',
 'NSRGY': 'Switzerland',
 'NTDOY': 'Japan',
 'NTES': 'China',
 'NVS': 'Switzerland',
 'ORAN': 'France',
 'PBR': 'Brazil',
 'PDD': 'China',
 'PKX': 'South Korea',
 'QFIN': 'China',
 'RDY': 'India',
 'RELX': 'United Kingdom',
 'RENOY': 'Unknown',
 'RHHBY': 'Switzerland',
 'RIO': 'Australia',
 'RY': 'Canada',
 'SAN': 'France',
 'SAP': 'Germany',
 'SBS': 'Brazil',
 'SFTBY': 'Japan',
 'SHEL': 'United Kingdom',
 'SHG': 'South Korea',
 'SHOP': 'Canada',
 'SID': 'Brazil',
 'SIEGY': 'Germany',
 'SKM': 'South Korea',
 'SMFG': 'Japan',
 'SONY': 'Japan',
 'SU': 'Canada',
 'TAL': 'China',
 'TCLRY': 'Australia',
 'TCOM': 'Singapore',
 'TD': 'Canada',
 'TECK': 'Canada',
 'TIGR': 'Singapore',
 'TIMB': 'Brazil',
 'TLSYY': 'Australia',
 'TM': 'Japan',
 'TME': 'China',
 'TRP': 'Canada',
 'TSM': 'Taiwan',
 'TTNDY': 'Hong Kong',
 'TU': 'Canada',
 'TUYA': 'China',
 'UBS': 'Switzerland',
 'UL': 'United Kingdom',
 'UMC': 'Taiwan',
 'VALE': 'Brazil',
 'VEDL': 'Unknown',
 'VOD': 'United Kingdom',
 'VWAGY': 'Germany',
 'WB': 'China',
 'WIT': 'India',
 'WOWOY': 'Australia',
 'WPM': 'Canada',
 'XP': 'Brazil',
 'XPEV': 'China',
 'YMM': 'China',
 'YSG': 'China',
 'ZLAB': 'China',
 'ZTO': 'China'}